import Head from 'next/head'
import Link from 'next/link'
import { PaddleLoader } from '@/components/PaddleLoad'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const openCheckout  = () => { 
    Paddle.Checkout.open({ product: 49368 }); 
  }

  const updateOverlaySubscription = () => {
    Paddle.Checkout.open({
      override: 'https://sandbox-subscription-management.paddle.com/subscription/462194/hash/411ab5a7f91a549b3de2e5922c4d50524ea5d6a061aeedc48debebe700cda421/manage-subscription',
      method: 'overlay',
      // frameTarget: 'checkout-container', // The className of your checkout <div>
      // frameInitialHeight: 416,
      // frameStyle: 'background-color: transparent; border: none;'    // Please ensure the minimum width is kept at or above 312px.
  })
  }

  const updateInlineSubscription = () => {
    Paddle.Checkout.open({
      override: 'https://sandbox-subscription-management.paddle.com/subscription/462194/hash/411ab5a7f91a549b3de2e5922c4d50524ea5d6a061aeedc48debebe700cda421/manage-subscription',
      method: 'inline',
      frameTarget: 'checkout-container', // The className of your checkout <div>
      frameInitialHeight: 416,
      frameStyle: 'width:100%; min-width:312px; background-color: transparent; border: none;'    // Please ensure the minimum width is kept at or above 312px.
  
  })
  }

  return (
    <>
      <Head>
        <title>Franklin Briones LLC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-sm mx-auto flex-col space-y-10 text-center ">
        <PaddleLoader />
        
        <h1 className='text-6xl flex py-14'>Welcome to my web store</h1>
        
        <Link href="/overlay" className="p-5 text-3xl text-center text-orange-200 border-4 border-white">See Overlay Checkout</Link>
        
        <Link href="/inline" className='p-5 text-3xl flex text-center text-pink-300 border-4 border-white'>See Inline Checkout</Link>
        
        <button onClick={updateInlineSubscription} className='p-4 border-2 border-white'>Update Subscription Inline</button>
        
        <div className="checkout-container"></div>
        
        <button onClick={updateOverlaySubscription} className='p-4 border-2 border-white'>Update Subscription Overlay</button>
      </main>
    </>
  )
}
