import Head from 'next/head'
import { Inter } from 'next/font/google'
import Pricing from '@/components/Pricing';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Franklin Briones LLC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />

        <h1 className="flex justify-center p-5 text-gray-200 text-7xl">Welcome to my web store</h1>
        <Pricing />
        <div className="checkout-container"></div>


      </main>
    </>
  )
}
