import Head from 'next/head'
import Link from 'next/link'
import { PaddleLoader } from '@/components/PaddleLoad'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    
    function openCheckout() {
    var form = document.getElementById('pre-checkout');
    const productId = form.products.value==="1" ? 49368
        : form.products.value==="2" ? 49374 
        : 49376;
        Paddle.Checkout.open({
            method: 'inline',
            product: productId,
            email: form.useremail.value,
            country: form.country.value,
            postcode: form.postalcode.value,
            successCallback: function checkoutComplete(data) {
                document.getElementById('event-data').innerHTML=JSON.stringify(data, null, 2)
                // Order data, downloads, receipts etc... available within 'data' variable
                console.log(data);
                // document.getElementById("thankyou-container").innerHTML = `
                //     <h3>Thank you for the purchase</h3>
                //     <p>Your receipt URL is: <a href=${receiptLink}>${receiptLink}</a></p>
                //     <p>Your email used is: ${orderEmail}</p>
                //     <p>Your order ID is: ${orderId}</p>`
            },
            closeCallback: function checkoutClosed(data) {
                console.log(data);
                window.open("https://www.theonion.com", "_blank"); 
            } ,
            allowQuantity: false,
            disableLogout: true,
            frameTarget: 'checkout-container', // className of your checkout <div>
            frameInitialHeight: 450, // `450` or above
            frameStyle: 'width:100%; min-width:312px; background-color: transparent; border: none;' // `min-width` must be set to `286px` or above with checkout padding off; `312px` with checkout padding on.
        });
    }

  return (
    <>
      <Head>
        <title>Inline</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex-col text-center">
        <PaddleLoader />
        <Link href="/" className=' text-2xl'>Go back Home</Link>
        <h1 className=' text-xl'>Welcome to my inline checkout web store</h1>
        <h2 className={styles.h2}>Please reload to see prices update below</h2>
        <br />


        <p>Grab your copy of FDB Software download 1 for just <span className="paddle-gross" data-product="49368">$0</span>!</p>
        <p>Grab your copy of FDB Software download 2 for just <span className="paddle-gross" data-product="49374">$0</span>!</p>
        <p>Grab your copy of FDB Software download 3 for just <span className="paddle-gross" data-product="49376">$0</span>!</p>
        <br />

        <div className='thankyou-container'></div>
        <form id="pre-checkout">
            <select id="products" name="products">
                <option value="1">Download 1</option>
                <option value="2">Download 2</option>
                <option value="3">Download 3</option>
              </select>
            <input id="useremail" type="text" placeholder="Email address" />
            <input id="country" type="text" placeholder="US or GB" />
            <input id="postalcode" type="text" placeholder="78702" />
        </form>
        <div id='checkout-container' className='checkout-container'></div>


        <button onClick={openCheckout}>Buy My Product</button>
        <pre height="100px" id='event-data'>This is where event-data will populate when a successful checkout occurs.</pre>
      </main>
    </>
  )
}
