import Head from 'next/head'
import { PaddleLoader } from '@/components/PaddleLoad'

export default function Home() {


  const openCheckout  = () => { 
    Paddle.Checkout.open({ product: 49368 }); 
  }

  return (
    <>
      <Head>
        <title>Overlay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-rows-2 gap-3 place-items-center p-30">
        <PaddleLoader />
        <h1 className="text-4xl pt-10">Welcome to my overlay checkout web store</h1>
        <a href='#!' className='paddle_button' data-product='49368'>Buy Now using HTML Attributes!</a>
        <button className="flex justify-center text-3xl border border-yellow-300 p-10" onClick={()=> {
          Paddle.Checkout.open({
            product: 49368,
            coupon: "10off"
          })
        }}>Buy now using Checkout.Open() method</button>
      </main>
    </>
  )
}
