import Head from 'next/head'
import { PaddleLoaderPB } from '@/components/PaddleLoadPB';

export default function Home() {


  return (
    <>
      <Head>
        <title>Overlay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-rows-2 gap-3 place-items-center p-30">
        <PaddleLoaderPB />
        <h1 className="text-4xl pt-10">Welcome to my overlay checkout web store</h1>
        <a
          href='#'
          class='paddle_button'
          data-theme='none'
          data-items='[
            {
              "priceId": "pri_01hd6m4j9h7fmxpx3aeaghzqaa",
              "quantity": 1
            }
          ]'
        >Buy now using HTML Attributes!</a>
        <a
          href='#'
          class='paddle_button'
          data-theme='none'
          data-items='[
            {
              "priceId": "pri_01hf7es7z2jez9834v9ehjhaqv",
              "quantity": 1
            }
          ]'
        >Save Card Details for future purchases!</a>
        <button className="flex justify-center text-3xl border border-red-300 p-10" onClick={() => {
          let request = {
            items: [{
                quantity: 1,
                priceId: 'pri_01hms0pm45jehb3m5cgr19wqqp',
              }
            ],
            address: {
              countryCode: 'KR'
            }
          }
          

          Paddle.PricePreview(request)
          .then((result) => {
            console.log(result);
          })
          .catch((error) => {
            console.error(error);
          });
        
        }}>console log price</button>
        <button className="flex justify-center text-3xl border border-yellow-300 p-10" onClick={() => {
          Paddle.Checkout.open({
            settings: {
              theme: "none",
            },
            items: [
              {
                priceId: 'pri_01hd6m4j9h7fmxpx3aeaghzqaa',
                quantity: 1
              }
            ]
          })
        }}>Buy now using Checkout.Open() method</button>
      </main>
    </>
  )
}
