import Head from 'next/head'
import { PaddleLoader } from '@/components/PaddleLoad'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const openCheckout  = () => { 
    Paddle.Checkout.open({ product: 49368 }); 
  }

  return (
    <>
      <Head>
        <title>Overlay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PaddleLoader />
        <h1>Welcome to my overlay checkout web store</h1>
        {/* <a href='#!' className='paddle_button' data-product='49368'>Buy Now!</a> */}
        <button onClick={()=> {
          Paddle.Checkout.open({
            product: 49368
          })
        }}>Buy My Product</button>
        {/* <pre>{JSON.stringify(json, null, 2)}</pre> */}
      </main>
    </>
  )
}
