import Head from 'next/head'
import { PaddleLoaderPB } from '@/components/PaddleLoadPB'

export default function Home() {

  const openCheckout = () => {
    Paddle.Checkout.open({
      settings: {
        theme: "light",
      },
      items: [
        {
          priceId: 'pri_01h0njbghz7gx8c8dvndqx573d',
          quantity: 5
        },
        {
          priceId: 'pri_01h0nje88dgdwy8krp2jyt0zy3',
          quantity: 1
        }
      ]});
    }


  return (
    <>
      <Head>
        <title>Overlay in PB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <PaddleLoaderPB />
        <h1>Welcome to my overlay checkout web store for Paddle Billing</h1>
        <br />
        <a href="#!"
          className="paddle_button"
          data-theme="light"
          data-locale="en"
          data-items='[
            {
              "priceId": "pri_01h0njbghz7gx8c8dvndqx573d",
              "quantity": 5
            },
            {
              "priceId": "pri_01h0nje88dgdwy8krp2jyt0zy3",
              "quantity": 1
            }
          ]' >
          Buy now using HTML data attributes
        </a>

        <br />
        <button onClick={() => {
          Paddle.Checkout.open({
            items: [
              {
                priceId: 'pri_01h0nje88dgdwy8krp2jyt0zy3',
                quantity: 1
              },
              {
                priceId: 'pri_01h0njbghz7gx8c8dvndqx573d',
                quantity: 1
              }
            ]
          });
        }}>Buy now using onClick event handler</button>

        <br />
        <a href='#' onClick={openCheckout}>Buy now using JS function</a>

      </main>
    </>
  )
}
