import Head from 'next/head'
import { PaddleLoaderPB } from '@/components/PaddleLoadPB';

export default function Home() {



  return (
    <>
      <Head>
        <title>Overlay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-rows-2 gap-3 place-items-center p-30">
        <PaddleLoaderPB />
        <h1>Pay here</h1>
      </main>
    </>
  )
}
